version: "3.9"
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    container_name: postgres
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./persistent-data/${DB_HOST}:/var/lib/postgresql/data
      - ./src/database/migration.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
  alexandria-indexer:
    build: ./
    restart: on-failure
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - postgres
  pgadmin:
      user: root
      image: dpage/pgadmin4
      restart: always
      volumes:
        - ./persistent-data/pgadmin4:/var/lib/pgadmin
        - ./servers.json:/pgadmin4/servers.json
      env_file:
        - .env
      ports:
      - 5050:80
      networks:
        - default
      depends_on:
      - postgres
  graphql-engine:
    image: hasura/graphql-engine:latest
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - postgres
volumes:
  persistent-data:
networks:
  default:
    name: ${DOCKER_NETWORK}
    ipam:
      driver: default
      
