version: "3.9"
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./persistent-data/${DB_HOST}:/var/lib/postgresql/data
      - ./src/database/migration.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
  alexandria-indexer:
    build: ./
    restart: on-failure
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - postgres
  pgadmin:
      image: dpage/pgadmin4
      restart: always
      volumes:
        - ./persistent-data/pgadmin:/var/lib/pgadmin
      depends_on:
      - postgres
      ports:
      - 5050:80
      env_file:
        - .env
  graphql-engine:
    image: hasura/graphql-engine:latest
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - postgres
volumes:
  persistent-data:
networks:
  default:
    name: ${DOCKER_NETWORK}
    ipam:
      driver: default
      
